[build]
  command = "bun install && bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  BUN_VERSION = "latest"
  PRISMA_SKIP_POSTINSTALL_GENERATE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
